/*
 * ExpressionCalculator
 *
 * No description
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ExpressionCalculator.Api.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ExpressionCalculation :  IEquatable<ExpressionCalculation>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ExpressionCalculation" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="Expression">Expression.</param>
        /// <param name="Result">Result.</param>
        /// <param name="DateGenerated">DateGenerated.</param>
        public ExpressionCalculation(int? Id = default(int?), string Expression = default(string), decimal? Result = default(decimal?), DateTime? DateGenerated = default(DateTime?))
        {
            this.Id = Id;
            this.Expression = Expression;
            this.Result = Result;
            this.DateGenerated = DateGenerated;
            
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="Id")]
        public int? Id { get; set; }
        /// <summary>
        /// Gets or Sets Expression
        /// </summary>
        [DataMember(Name="Expression")]
        public string Expression { get; set; }
        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name="Result")]
        public decimal? Result { get; set; }
        /// <summary>
        /// Gets or Sets DateGenerated
        /// </summary>
        [DataMember(Name="DateGenerated")]
        public DateTime? DateGenerated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExpressionCalculation {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Expression: ").Append(Expression).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  DateGenerated: ").Append(DateGenerated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((ExpressionCalculation)obj);
        }

        /// <summary>
        /// Returns true if ExpressionCalculation instances are equal
        /// </summary>
        /// <param name="other">Instance of ExpressionCalculation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExpressionCalculation other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Expression == other.Expression ||
                    this.Expression != null &&
                    this.Expression.Equals(other.Expression)
                ) && 
                (
                    this.Result == other.Result ||
                    this.Result != null &&
                    this.Result.Equals(other.Result)
                ) && 
                (
                    this.DateGenerated == other.DateGenerated ||
                    this.DateGenerated != null &&
                    this.DateGenerated.Equals(other.DateGenerated)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                    if (this.Expression != null)
                    hash = hash * 59 + this.Expression.GetHashCode();
                    if (this.Result != null)
                    hash = hash * 59 + this.Result.GetHashCode();
                    if (this.DateGenerated != null)
                    hash = hash * 59 + this.DateGenerated.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(ExpressionCalculation left, ExpressionCalculation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ExpressionCalculation left, ExpressionCalculation right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
